[tool.black]
line-length = 90
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | migrations
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
