name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: enrollxchange
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
#           dontuseforce: false #OPTIONAL and DEFAULT - false
#           appdir: "" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder
